site_name: "POS-Docs"
site_url: https://pchs-projectprogramming.github.io/POS-Docs/
site_author: "PCHS-ProjectProgramming 22/23"
copyright: Copyright &copy; 2022 - 2023 PCHS Project

extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.sections
    - navigation.instant
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  logo: assets/favicon.png
  favicon: assets/favicon.png

extra:
  homepage: https://PCHS-ProjectProgramming.github.io/POS-Docs
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/PCHS-ProjectProgramming/Android-POS
  - icon: fontawesome/brands/discord
    link: https://discord.gg/K9ueFm8a2P
  - icon: fontawesome/brands/usb
    link: secrets/natalie.html

nav:
  - Home: https://PCHS-ProjectProgramming.github.io/POS-Docs
  - Documentation: https://PCHS-ProjectProgramming.github.io/POS-Docs
  - Github: https://github.com/PCHS-ProjectProgramming
  # Populate Nav Eventually
