site_name: Android-POS Docs

theme:
  palette:
    scheme: slate
    primary: black
    accent: red
    
# Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
